### ISSUE TITLE
[INTENDED] Angry Endermen don't seem to extend Endermen behaviour

### ISSUE THREAD

**Issue by cristianmartin** [chylex/Hardcore-Ender-Expansion#132] opened 2015-08-05 11:01 UTC
This seems to be causing issues with other mods such as EssentialCraft's Ender Generator, but they are also not dropping things like RFTools dimlets. Here's an example of the EC3 issue: https://github.com/Modbder/EssentialCraft3/issues/23

**Comment by chylex** [comment] 2015-08-05 11:56
That's intended, they don't behave like regular Endermen and they're not supposed to interact with other mods in this way since they are much easier to farm.

**Comment by cristianmartin** [comment] 2015-08-05 12:07
I disagree on that. For instance, any pack with EnderIO will allow you to pick up something common like a zombie spawner and make it spawn Enderman. Another example could be RFTools lasers. Give them energy and pearls and boom, Enderman farm. In Thaumic Tinkerer, you just need to harvest essences and use the Necromancy Table to spawn them. The list goes on and on.

Angry Enderman require you go to The End and pick up Death Flowers (if the dragon doesn't kill you first), which make them a bit more difficult to farm than normal Enderman.

**Comment by chylex** [comment] 2015-08-05 12:37
You don't need Death Flowers, there are Angry Enderman spawners all over the place. Angry ones aren't vanilla-like Endermen, they have different drops, different spawning conditions, abilities and stats. If other mods allows you to change spawners to have infinite Endermen, that's not really my problem, and then why would you even need Angry Endermen to get regular Enderman drops in the first place?

**Comment by cristianmartin** [comment] 2015-08-05 12:45
Well my particular problem is specific for FTB Horizons II, there seems to be no other way to farm Enderman, so as I said is very particular.

About the spawners, I opened issue 131. They don't work once you move them (at least in the Overworld).

**Comment by chylex** [comment] 2015-08-05 12:48
If there's no other way of farming them, maybe that was intentional? Ask the makers of Horizons II.

#131 has been answered. It's not an error in HEE, but even if it worked, the spawners would stop working after moving.

**Comment by cristianmartin** [comment] 2015-08-05 12:50
I did not move it with EC3, I did it with a cardboard box from Mekanism. The error with EC3 is apparently going to be solved to accept TileEntityCustomSpawner and not to crash the entire client when you try to interact with it.

**Comment by chylex** [comment] 2015-08-05 12:52
Right; some mods only check for block type and not the TE type, that's not something I can really control. Either way, doesn't matter how you moved it, the spawner shouldn't work anymore.

**Comment by chylex** [comment] 2015-08-05 22:05
Closing for now, it's not worth the effort of working around vanilla Enderman just to have mod compatibility since regular Endermen are still available.

**Closed by chylex** 2015-08-05 22:05 UTC
Labels: bug

**Comment by nitwhiz** [comment] 2018-02-15 19:25
I know this is hella old but..

Where, I can't find a single vanilla enderman in the end after beating the dragon?
Farming simple things like EnderIO heads is a pain this way.:/

(Using 1.7.10 version)

**Comment by chylex** [comment] 2018-02-15 19:40
I don't recall EnderIO having any issues with HEE's Endermen that naturally spawn in the End. Angry Endermen are not intended for farming and won't work, but naturally spawned Endermen should be fine.

**Comment by TylorBane** [comment] 2018-06-15 19:32
I know this is closed, but I'm having a few issues and I'm not sure how to solve them... I'm trying to use mods like EC3 and mutant creatures, and the changes you've done to the "vanilla" endermen, are causing them to not be affected by things like ring effects that keep them from teleporting as well as chemicalX not being able to turn them into a mutant

**Comment by TylorBane** [comment] 2018-06-15 19:35
i wouldn't care if things like angry endermen couldn't be affected by these things, thats fine, but the vanilla ones have been changed to a new class and it causes other mods to not be able to enable their code properly

**Comment by chylex** [comment] 2018-06-15 19:42
HEE 1 is discontinued.

**Comment by TylorBane** [comment] 2018-06-15 19:46
so is there nothing i can do to fix these issues? theres not even a config option to turn off your code from "taking over" vanilla endermen

**Comment by chylex** [comment] 2018-06-15 19:52
The mod extends vanilla Endermen, so if some mod isn't recognizing them for mutations or whatever, that's not my fault. With teleportation, I'm pretty sure none of the HEE 1 mobs can be stopped from teleporting, because it's literally just changing their location but without using Forge events to ask other mods. That will be fixed in HEE 2, but there will be no more updates to HEE 1.

**Comment by TylorBane** [comment] 2018-06-15 19:55
while yes you extend vanilla endermen, you also replace the vanilla class with your own, waila and other mods report "vanilla" endermen, as being owned by HEE

**Comment by TylorBane** [comment] 2018-06-15 19:56
either way, thanks for the information at least

**Comment by chylex** [comment] 2018-06-15 20:08
A mod that checks for Endermen shouldn't care which mod owns them, if they don't change that then it won't work with HEE 2 either.

**Comment by TylorBane** [comment] 2018-06-16 08:37
not that i really want to continue this any further, but i think the problem is the fallowing, to my knowlage, mods that look for other mods items/entitys, so on, look for modname:classpath to some degree, if this is true, then the fact that "vanilla" endermen are now HEE:endermen instead of minecraft:endermen is screwing things up but thats just my take on it *shrugs* or at least what i've seen on the inner workings of 1.7.10

**Comment by chylex** [comment] 2018-06-16 14:43
Entities could always be checked by their base type, mods can either check for that, or they can restrict it to be incompatible with mods that replace vanilla entities, but that actually takes more work on their side and is not my problem.

**Comment by TylorBane** [comment] 2018-06-16 19:32
from what i understand, searching for things like modid:whatYourLookingFor seems to be some sort of forge standard almost every single config i've gone through (i am currently trying to make a server with over 300 mods, i go through a lot of configs) ask for items/blocks/entitys in this fassion

**Comment by chylex** [comment] 2018-06-16 19:37
That's for configs, in code entities are normally checked by the class/type.
