### ISSUE TITLE
Thaumcraft and HEE makes server crash

### ISSUE THREAD

**Issue by adamsonich** [chylex/Hardcore-Ender-Expansion#165] opened 2015-12-30 15:27 UTC
If i have pouch in inventory and destroy thaum blocks server crash.

[20:11:16] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.entity.player.PlayerDestroyItemEvent@47d914ac:
java.lang.NullPointerException
        at chylex.hee.mechanics.charms.handler.CharmEvents.onItemDestroyed(CharmEvents.java:440) ~[CharmEvents.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_1035_CharmEvents_onItemDestroyed_PlayerDestroyItemEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?]
        at net.minecraftforge.event.ForgeEventFactory.onPlayerDestroyItem(ForgeEventFactory.java:106) [ForgeEventFactory.class:?]
        at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:395) [mx.class:?]
        at thaumcraft.common.entities.ai.interact.AIUseItem.click(AIUseItem.java:158) [AIUseItem.class:?]
        at thaumcraft.common.entities.ai.interact.AIUseItem.func_75246_d(AIUseItem.java:99) [AIUseItem.class:?]
        at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:103) [uj.class:?]
        at net.minecraft.entity.EntityLiving.func_70619_bc(EntityLiving.java:540) [sw.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1774) [sv.class:?]
        at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:367) [sw.class:?]
        at thaumcraft.common.entities.golems.EntityGolemBase.func_70636_d(EntityGolemBase.java:354) [EntityGolemBase.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611) [sv.class:?]
        at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206) [sw.class:?]
        at net.minecraft.world.World.func_72866_a(World.java:2070) [ahb.class:?]
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648) [mt.class:?]
        at net.minecraft.world.World.func_72870_g(World.java:2034) [ahb.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1887) [ahb.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) [mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[20:11:17] [Server thread/ERROR] [FML]: Index: 4 Listeners:
[20:11:17] [Server thread/ERROR] [FML]: 0: NORMAL
[20:11:17] [Server thread/ERROR] [FML]: 1: ASM: forestry.core.items.ItemForestryPickaxe@68bc7238 onDestroyCurrentItem(Lnet/minecraftforge/event/entity/player/PlayerDestroyItemEvent;)V
[20:11:17] [Server thread/ERROR] [FML]: 2: ASM: forestry.core.items.ItemForestryShovel@23d6877f onDestroyCurrentItem(Lnet/minecraftforge/event/entity/player/PlayerDestroyItemEvent;)V
[20:11:17] [Server thread/ERROR] [FML]: 3: LOWEST
[20:11:17] [Server thread/ERROR] [FML]: 4: ASM: chylex.hee.mechanics.charms.handler.CharmEvents@2ede5b7e onItemDestroyed(Lnet/minecraftforge/event/entity/player/PlayerDestroyItemEvent;)V
[20:11:20] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.entity.player.PlayerDestroyItemEvent@127266e6:
java.lang.NullPointerException
        at chylex.hee.mechanics.charms.handler.CharmEvents.onItemDestroyed(CharmEvents.java:440) ~[CharmEvents.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_1035_CharmEvents_onItemDestroyed_PlayerDestroyItemEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?]
        at net.minecraftforge.event.ForgeEventFactory.onPlayerDestroyItem(ForgeEventFactory.java:106) [ForgeEventFactory.class:?]
        at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:395) [mx.class:?]
        at thaumcraft.common.entities.ai.interact.AIUseItem.click(AIUseItem.java:158) [AIUseItem.class:?]
        at thaumcraft.common.entities.ai.interact.AIUseItem.func_75246_d(AIUseItem.java:99) [AIUseItem.class:?]
        at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:103) [uj.class:?]
        at net.minecraft.entity.EntityLiving.func_70619_bc(EntityLiving.java:540) [sw.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1774) [sv.class:?]
        at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:367) [sw.class:?]
        at thaumcraft.common.entities.golems.EntityGolemBase.func_70636_d(EntityGolemBase.java:354) [EntityGolemBase.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611) [sv.class:?]
        at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206) [sw.class:?]
        at net.minecraft.world.World.func_72866_a(World.java:2070) [ahb.class:?]
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648) [mt.class:?]
        at net.minecraft.world.World.func_72870_g(World.java:2034) [ahb.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1887) [ahb.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) [mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[20:11:20] [Server thread/ERROR] [FML]: Index: 4 Listeners:
[20:11:20] [Server thread/ERROR] [FML]: 0: NORMAL
[20:11:20] [Server thread/ERROR] [FML]: 1: ASM: forestry.core.items.ItemForestryPickaxe@68bc7238 onDestroyCurrentItem(Lnet/minecraftforge/event/entity/player/PlayerDestroyItemEvent;)V
[20:11:20] [Server thread/ERROR] [FML]: 2: ASM: forestry.core.items.ItemForestryShovel@23d6877f onDestroyCurrentItem(Lnet/minecraftforge/event/entity/player/PlayerDestroyItemEvent;)V
[20:11:20] [Server thread/ERROR] [FML]: 3: LOWEST
[20:11:20] [Server thread/ERROR] [FML]: 4: ASM: chylex.hee.mechanics.charms.handler.CharmEvents@2ede5b7e onItemDestroyed(Lnet/minecraftforge/event/entity/player/PlayerDestroyItemEvent;)V

HardcoreEnderExpansion  MC-1.7.10  v1.8.4.jar
Thaumcraft-1.7.10-4.2.3.5.jar

**Comment by adamsonich** [comment] 2015-12-30 15:46
ok
I looked  Hardcore-Ender-Expansion/src/main/java/chylex/hee/mechanics/charms/handler/CharmEvents.java
and want to add some information:
I use one of thaum wands with excavation foci.
and I dont see and chance why minecraft execute function CharmEvents.java@"onItemDestroyed"

**Comment by chylex** [comment] 2015-12-30 15:52
You have active golems somewhere, breaking blocks is just a coincidence. Can you get back in the world? If not, can you send me the world and a full list of mods you have installed? If you can get back, I'm afraid the golem will have disappeared, not sure what to do then because I haven't ever done anything with golems.

**Comment by adamsonich** [comment] 2015-12-30 15:54
Yep, world after server restart is ok

**Comment by adamsonich** [comment] 2015-12-30 16:03
As I can think if thaum golems breaks a blocks minecraft calls function CharmEvents.java@"onItemDestroyed" 
but why world crash if I break blocks in same time?

**Comment by chylex** [comment] 2015-12-30 16:09
Really not sure why it crashed... I assume the fake player golems use was null, but that shouldn't happen. Are you using cauldron?

**Comment by adamsonich** [comment] 2015-12-30 16:12
may be minecraft send "e" as null?
No, we dont use cauldron.

**Comment by chylex** [comment] 2015-12-30 16:17
I assume a null entity is somehow happening... I'll just add a check and backport it. Do you have a reliable way of reproducing the crash? It should happen when a golem uses an item and the item breaks, I would like to test it myself to make sure the fix works but I need a world where I can reproduce the crash.

**Comment by adamsonich** [comment] 2015-12-30 16:29
world with mods?
ok, i will upload it tomorrow.

**Comment by chylex** [comment] 2015-12-30 16:30
World where you can reliably replicate the crash, because I need to test it.

**Comment by chylex** [comment] 2015-12-30 16:41
Maybe @Azanor can see what's going on? It crashes on this line in a PlayerDestroyItemEvent handler:
```
if (e.entity.worldObj.isRemote)return;
```

**Comment by chylex** [comment] 2016-01-07 10:44
I added some null checks, will close the issue after I port it to HEE 2 as well.

**Closed** 2016-01-07 11:40 UTC
Labels: crash
