### ISSUE TITLE
[WTF] Crash when Chromaticraft V11a is present

### ISSUE THREAD

**Issue by Lebleus** [chylex/Hardcore-Ender-Expansion#170] opened 2016-02-27 11:45 UTC
Hello, with the last version of HEE, the game can't be launched with the new version of Chromaticraft (V11a). It seems to be a bug with Sound Registering or something.

Here's the crash log.

`java.lang.ArrayIndexOutOfBoundsException: 9
	at java.util.EnumMap.put(Unknown Source)
	at java.util.EnumMap.put(Unknown Source)
	at Reika.DragonAPI.Libraries.ReikaRegistryHelper.addSoundCategory(ReikaRegistryHelper.java:292)
	at Reika.ChromatiCraft.ChromaClient.registerSounds(ChromaClient.java:148)
	at Reika.ChromatiCraft.ChromatiCraft.preload(ChromatiCraft.java:319)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`

I have also reported it to Reika (Chromaticraft Mod Dev'). 

I hope you will fix the problem quickly.

**Comment by chylex** [comment] 2016-02-27 12:55
The crash has no information about HEE causing the issue, and I don't touch sound categories (only music types, which I've been doing for years anyways). Need info on your mod setup and replication with different HEE versions.

@ReikaKalseki any idea?
https://github.com/ReikaKalseki/DragonAPI/blob/master/Libraries/ReikaRegistryHelper.java#L292

**Comment by ReikaKalseki** [comment] 2016-02-27 20:32
As of v11 I add a custom sound category using Forge's EnumHelper. I know it works both in the dev environment and in my pack with some 180 mods, yet apparently HEE causes it to fail, not on the actual expansion of the enum, but the later reregistration of the volume settings, where `Minecraft.getMinecraft().gameSettings.mapSoundLevels` does not have the expected size....five lines after it was explicitly assigned. Do you modify that (normally private, but ATed to public for me) field or the SoundCategory class in any way?

**Comment by chylex** [comment] 2016-02-27 20:38
I don't touch mapSoundLevels nor SoundCategory, I only modify the music ticker and add a new entry to MusicType during SoundLoadEvent. All related code is in chylex.hee.sound (1.7.10-v1.8.5 branch).

**Comment by ReikaKalseki** [comment] 2016-02-27 20:46
Can you try temporarily turning that off and seeing if the crash still happens?

**Comment by chylex** [comment] 2016-02-27 20:55
The crash doesn't happen with the music replacement enabled. Running HEE 1.8.5, DragonAPI + CC V11a, Java8Checker v1.2. I asked OP to clarify their mod setup, can't replicate the issue with only those mods.

**Comment by ReikaKalseki** [comment] 2016-02-27 21:02
The issue on my tracker mentions previous HEE versions triggering the crash with 1.8.5 fixing it, whereas others contradicted that. Yet others said it was Java-version-specific.

**Comment by chylex** [comment] 2016-02-27 21:09
Doesn't trigger with v1.8.4 either. Can't test on Java 7 because it's some portable probably 32bit version and I had to set it to 5 GB total just to get CC to run..

**Comment by aking4125** [comment] 2016-02-27 21:12
Perhaps it'll help if I upload my full crashlog? Since 1.8.5 crashes for me? Maybe my mod list might provide some insight or ?
[crash-2016-02-27_13.10.41-client.txt](https://github.com/chylex/Hardcore-Ender-Expansion/files/149564/crash-2016-02-27_13.10.41-client.txt)

**Comment by ReikaKalseki** [comment] 2016-02-28 00:06
I am on Java 7.55 with no crases.

**Comment by Lebleus** [comment] 2016-02-28 09:09
I was using java 8.31 when the crash happens.
I updated Java to latest version (8.73) and the crash happens again.

Also I tried these modpack configuration to have more informations about the crash ;

- Modpack alone => no crash
- Modpack + HEE => no crash
- Modpack + CC => no crash
- Modpack + HEE + CC => Crash

PS : I added my crash log file   : 
[crash-2016-02-28_10.05.30-client.txt](https://github.com/chylex/Hardcore-Ender-Expansion/files/149826/crash-2016-02-28_10.05.30-client.txt)

**Comment by Dehietyi** [comment] 2016-02-28 21:52
I can confirm this. ^ Same exact thing with both HEE and CC installed. both HEE 1.8.4 and 1.8.5. Using newest version of CC v11b. If I take out either/or I do not get the crash. http://pastebin.com/bPC1RwAR

**Comment by chylex** [comment] 2016-02-29 10:19
Again, cannot replicate with only HEE and CC installed, plus the crash has no direct or logical link to HEE. If nobody can confirm that this crash happens with only HEE and CC installed, I will close the issue and ask to find the smallest amount of mods required to replicate the crash (suspecting it's a combination of HEE, CC, and another mod) and reporting it to them.

**Comment by dabaer** [comment] 2016-02-29 19:02
I said multiple times in the previous issue that I can only reproduce this crash with Forestry installed.

HEE+CC: https://gist.github.com/dabaer/b7f5d97fab4e10bb36ee (no crash)
Forestry+CC: https://gist.github.com/dabaer/9a2ea4a1684695ddd894 (no crash)
HEE+Forestry+CC https://gist.github.com/dabaer/796f3d031800b6be72a0 (crash)

**Comment by dabaer** [comment] 2016-02-29 19:06
It also looks like updating Forestry to latest fixed a previous crash while I was testing. I can now reproduce this crash with JUST HEE+Forestry+Reika et al:

https://gist.github.com/dabaer/fae5090c1fb57cf7a654

**Comment by ReikaKalseki** [comment] 2016-02-29 20:44
WTF...does Forestry add sound categories or modify the system? @mezz

**Comment by mezz** [comment] 2016-02-29 22:20
Forestry doesn't have and sounds, and doesn't use assembly or alter anything other than its own config files.

**Comment by ReikaKalseki** [comment] 2016-03-01 01:09
This officially makes no sense. Were this my issue tracker, the @#$&?! tag would be applied.

**Comment by dabaer** [comment] 2016-03-01 01:28
Sounds like a non-transient Heisenbug.

**Comment by dabaer** [comment] 2016-03-01 01:37
@ReikaKalseki were you able to reproduce this on your side? And are you able to see the other categories being added?

**Comment by ReikaKalseki** [comment] 2016-03-01 03:23
No and yes respectively, but my pack does not contain HEE.

**Comment by chylex** [comment] 2016-03-01 07:33
Title will have to do Reika :P

**Comment by aking4125** [comment] 2016-03-01 11:47
I can confirm that updating from Forestry from 4.2.5.53 to 4.2.9.57 did not fix the crash. Crash is still the same but here's the new updated crash file for more information.
[crash-2016-03-01_06.45.34-client.txt](https://github.com/chylex/Hardcore-Ender-Expansion/files/152651/crash-2016-03-01_06.45.34-client.txt)
.

**Comment by Teslapirate** [comment] 2016-03-02 02:57
I think this issue may be related to some sort of config setting / conflict. I was getting the same crash, I tried backing up and deleting my options.txt and reloaded, game loaded fine without further problems.

**Comment by aking4125** [comment] 2016-03-02 03:02
@Teslapirate Problem is. At Reikas issue tracker. I was told basically the same thing. New Instance and still get the same crash. Though who knows at this point.

**Comment by ReikaKalseki** [comment] 2016-03-02 03:28
Do either Forestry or HEE use EnumHelper? I am out of ideas.

**Comment by chylex** [comment] 2016-03-02 08:50
Yea, for MusicType https://github.com/chylex/Hardcore-Ender-Expansion/search?utf8=%E2%9C%93&q=EnumHelper

**Comment by ReikaKalseki** [comment] 2016-03-02 09:11
I wonder if EnumHelper is having some "leftover state" issue...

**Comment by chylex** [comment] 2016-03-02 09:28
For anyone with the issue, does it still happen if you disable all music related stuff in the HEE config? There are two options I think, disable both.

**Comment by aking4125** [comment] 2016-03-02 12:51
@chylex I'm gonna assume the two options would be _B:enableMusic=false_ & _B:removeVanillaDelay=false_  

The game still crashes with the same error. Here's another updated crash report just to see if anything change slightly. 
[crash-2016-03-02_07.49.11-client.txt](https://github.com/chylex/Hardcore-Ender-Expansion/files/154811/crash-2016-03-02_07.49.11-client.txt)

**Comment by chylex** [comment] 2016-03-02 12:56
@ReikaKalseki Could something be loading gamesettings, and thusly the enum map before the EnumHelper has a chance to modify the value list? The implementation of EnumMap creates the internal array on construction.

**Comment by Teslapirate** [comment] 2016-03-03 01:50
I tried setting B:enableMusic=false , still crashes. The other option ( removeVanillaDelay ) was already disabled.

**Comment by ReikaKalseki** [comment] 2016-03-03 06:07
> Could something be loading GameSettings

I explicitly assign and overwrite the map myself, though:
`Minecraft.getMinecraft().gameSettings.mapSoundLevels = new EnumMap(SoundCategory.class);`

**Comment by chylex** [comment] 2016-03-03 10:49
Right... what the fuck is going on then >.> it's not HEE music, if the configs are disabled EnumHelper doesn't trigger.

**Comment by ReikaKalseki** [comment] 2016-03-03 12:36
Now you know how I feel...

**Comment by chylex** [comment] 2016-03-03 12:50
I guess same as me, since apparently it's also an HEE issue somehow..

**Comment by dabaer** [comment] 2016-03-03 14:27
If Forestry is somehow involved, what else do you both have in common?

**Comment by ReikaKalseki** [comment] 2016-03-03 15:36
> Cause the sound engine runs in a different thread

The sound engine does, but the GameSettings do not, nor can anything else assign that map; I had to AT it just to be able to access it.

**Comment by chylex** [comment] 2016-03-03 16:52
No other ideas then.

**Comment by Lebleus** [comment] 2016-03-03 17:20
@ReikaKalseki You add an option in Music settings to configure Chromaticraft sound level right ? 

If you disable the code which add this option, does the bug happen again ?

You have bees in Chromaticraft, if they have sounds (or a music) and forestry load before chromaticraft, the config option is not added yet so the game crashes

I know, it's a bit weird to understand but the crash itself is weird

**Comment by ReikaKalseki** [comment] 2016-03-03 18:43
The dimension music and the bees have nothing to do with each other.

Also, no, there is no config, nor does Forestry loading first matter; GameSettings *should* initialize well before any mod gets to load.

**Comment by Teslapirate** [comment] 2016-03-04 02:24
A little additional information that might help: If I remove all the keybinding data (key_*) from options.txt, this crash does not occur. No keybinding data gets written on load/quit from then on until I change a key in the in-game menu. It writes all of the keys to options.txt, and this crash then occurs on subsequent loads.

**Comment by aking4125** [comment] 2016-03-04 02:33
I can confirm the above method for whatever reason worked.

**Comment by ReikaKalseki** [comment] 2016-03-04 03:21
![](http://i.imgur.com/bvjdh4X.png)

**Comment by Teslapirate** [comment] 2016-03-04 03:45
More information: After further testing I've found there seems to be a numerical limit to how many key_ entries there can be in options.txt. 62 key_ entries, loads fine. 63 entries, crash. Does not seem to matter what entries there are as long as that numerical limit is obeyed.

**Comment by Zsashas** [comment] 2016-03-04 03:54
I've only had this issue when using Java 8. When using Java 7, it's fine.

**Comment by dabaer** [comment] 2016-03-04 16:01
Unfortunately ~80% of our user base is on java 8 :<

**Comment by aking4125** [comment] 2016-03-04 16:13
I can confirm Java 7 U79 working. Java 8 U73 crashes with the same error.

**Comment by ReikaKalseki** [comment] 2016-03-04 20:55
This is *completely* incomprehensible. The *very nature* of JVMs is so that they should behave the same no matter what!

**Comment by dabaer** [comment] 2016-03-05 02:40
@LexManos maybe?

**Comment by sikerow** [comment] 2016-03-07 17:59
how do i enter  If I remove all the keybinding data (key_*) from options.txt that thingi plz help me

**Comment by sikerow** [comment] 2016-03-07 18:01
and what do i actully do if i find it

**Comment by Tigertycoon** [comment] 2016-03-12 14:07
I have the same crash even after i deleted HEE

**Comment by chylex** [comment] 2016-03-13 11:00
Uh... want to reopen the issue on CC tracker @ReikaKalseki? Apparently ^ it's now replicated without HEE, so I have even less of a fucking clue as to what might be happening.

**Comment by ReikaKalseki** [comment] 2016-03-13 20:18
I see noone clearly stating its occurrence being independent of the presence of HEE. I am just as clueless as you, and get the feeling that this is a classloading issue.

**Comment by chylex** [comment] 2016-03-13 22:26
The comment was removed, so nevermind..

**Comment by Tigertycoon** [comment] 2016-03-14 14:19
Sorry, but its right HEE is not the only mod thats causing this. I deleted my comment because i wanted to check which mods make the same crash happen too

**Comment by aking4125** [comment] 2016-03-14 17:29
@Tigertycoon And which mod also caused the same crash?

**Comment by Tigertycoon** [comment] 2016-03-14 20:13
Ok... it seems it's no other mod specifically but just the key thing again

**Comment by dabaer** [comment] 2016-03-15 04:24
@ReikaKalseki any luck on the keybind front? is this a vanilla limitation (while we're on that note :P)?

**Comment by ReikaKalseki** [comment] 2016-03-15 04:31
What would I do or test? I am on Java 7 and do not have issues, and I doubt it would be a good idea to put limits on the keybind system.

**Comment by dabaer** [comment] 2016-03-15 04:41
I'm not sure, and I didn't mean to put limits on it, I was wondering if there was a known limit (as with items, biomes, potions, etc) in correlation with java 8, and if there was any way to shim it to get around that limit.

**Comment by Tigertycoon** [comment] 2016-03-15 06:59
I... have an idea a mod with the name keybindingoverhaul exits. when first installed  it clears all keys. Then minecraft should statt an you Can define new keys... But not to much

**Comment by ReikaKalseki** [comment] 2016-03-15 13:55
I have never messed with the keybind system, but the only relation I can imagine between it and mapSoundLevels is that they are both stored in GameSettings.

**Comment by ReikaKalseki** [comment] 2016-03-15 15:59
Also, is CC really the first mod to add a custom sound category? If so, that would surprise me; if not, how does it work for them?

**Comment by chylex** [comment] 2016-03-15 16:08
I don't create new GameSettings anywhere, but I add keybindings.

**Comment by ReikaKalseki** [comment] 2016-03-22 13:56
I hopefully have a workaround: Can someone confirm this to be the accurate set of triggers?


	@SideOnly(Side.CLIENT)
	private static boolean useSoundHashMap() {
		return ModList.ENDEREXPANSION.isLoaded() && ModList.FORESTRY.isLoaded() && ReikaJVMParser.getJavaVersion(0) == 8 && KeyBinding.getKeybinds().size() >= 63;
	}

**Comment by Leguan12** [comment] 2016-03-22 20:01
I can't absolutely confirm it, but those will defenitely all return true in my currently erroring mod constellation, so from my perspective, yes it should be correct :+1:

**Comment by ReikaKalseki** [comment] 2016-03-22 20:03
I need to know that all of them are necessary conditions. I do not want to check things that do not actually trigger the issue and thus lock out some cases.

**Comment by Leguan12** [comment] 2016-03-22 21:37
I was able to reproduce it without HEE once though I was unable to find the mod that 'replaced' it...
If the log helps any, here it is: https://gist.github.com/Leguan12/bb3176e96690eca375c7/raw/d178606441951894afd52c978ed8cb654f53fce5/fml-client-latest.log_new

**Comment by aking4125** [comment] 2016-03-30 21:07
I can confirm the crash is still happening with Chromaticraft v12b. Updated Config here if anything. Java 8 U77. I'm guessing at this point it's a lost cause. I have no idea how to apply the above code.
[crash-2016-03-30_17.04.04-client.txt](https://github.com/chylex/Hardcore-Ender-Expansion/files/196440/crash-2016-03-30_17.04.04-client.txt)

**Comment by ReikaKalseki** [comment] 2016-03-30 21:17
Clearly the conditions given are inaccurate. This is why I asked for confirmation.

**Comment by rockachu2** [comment] 2016-04-01 21:32
I can confirm the issue is due to a limitations in the keybindings. I'm using all the above mods, java 8, and had the same crash upon adding HEE. I deleted ~10 lines from the options.txt (regardless of what they were) and the game successfully started up.

**Comment by SvEgiiVEteR** [comment] 2016-04-01 21:36
https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/719 and me

**Comment by rockachu2** [comment] 2016-04-01 21:59
I can confirm (with another huge set of mods -.-) that forestry + hee + cccraft together at least cause the issue. I'm checking whether forestry is necessary soon

**Comment by rockachu2** [comment] 2016-04-01 22:30
Removing forestry OR HEE stops the bug from triggering.

**Comment by Bogdan-G** [comment] 2016-04-01 22:56
It may be had to the debugger, and the stack trace to see?

**Comment by ReikaKalseki** [comment] 2016-04-02 01:32
It is a config now, so just set it and be done with it.

**Comment by aking4125** [comment] 2016-04-03 06:42
I'm assuming the config option is in the DragonAPI.cfg and is named _"B:"Use HashMap for Sound Categories - Only use if necessary"=true"_ ? I also enabled this option in the Chromaticraft.cfg _"B:"Use vanilla keybind system for ability selection GUI"=true"_ Just to be safe though I'm unsure if that destroyed something else or what.

If so, setting that gives a successful boot with HEE. A single player world was also successfully generated as well. Looking good so far.

**Comment by chylex** [comment] 2016-05-30 17:30
Resolved on CC side.

**Closed by chylex** 2016-05-30 17:30 UTC
Labels: crash
